# Generated by Django 4.2 on 2023-04-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_rename_iscomplete_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
    ]
